export const COLORS = {
  background: {
    primary: "#05070D",
    secondary: "#080B12",
    tertiary: "#0D111C",
    card: "#0F1423",
    cardHover: "#141B2D",
    elevated: "#1A2238",
  },
  accent: {
    cyan: "#00F5FF",
    purple: "#8B5CF6",
    blue: "#3B82F6",
    green: "#00FF9C",
    red: "#FF3B5C",
    orange: "#FF8C42",
    yellow: "#FFD700",
    pink: "#FF69B4",
  },
  text: {
    primary: "#E2E8F0",
    secondary: "#94A3B8",
    muted: "#64748B",
    accent: "#00F5FF",
  },
  border: {
    primary: "#1E293B",
    hover: "#334155",
    accent: "#00F5FF",
  },
  status: {
    online: "#00FF9C",
    idle: "#FFD700",
    dnd: "#FF3B5C",
    offline: "#64748B",
  },
  security: {
    nominal: "#00FF9C",
    elevated: "#FFD700",
    high: "#FF8C42",
    critical: "#FF3B5C",
  },
} as const;

export const CHARACTERS = {
  nova: {
    id: "nova" as const,
    name: "NOVA",
    title: "Main AI Assistant",
    color: "#00F5FF",
    emoji: "🔮",
    personality: "Helpful, intelligent, and forward-thinking",
    tone: "Professional yet friendly",
    responseStyle: "Clear and concise with technical depth when needed",
    module: "Command Center",
    expression: "idle" as const,
  },
  vex: {
    id: "vex" as const,
    name: "VEX",
    title: "Security Intelligence",
    color: "#FF3B5C",
    emoji: "🛡️",
    personality: "Vigilant, analytical, and protective",
    tone: "Serious and alert",
    responseStyle: "Precise threat assessments with actionable intelligence",
    module: "Security",
    expression: "idle" as const,
  },
  aria: {
    id: "aria" as const,
    name: "ARIA",
    title: "Community Assistant",
    color: "#8B5CF6",
    emoji: "💬",
    personality: "Warm, welcoming, and community-focused",
    tone: "Friendly and approachable",
    responseStyle: "Engaging and supportive responses",
    module: "Community",
    expression: "idle" as const,
  },
  kai: {
    id: "kai" as const,
    name: "KAI",
    title: "Developer Assistant",
    color: "#3B82F6",
    emoji: "⚡",
    personality: "Technical, precise, and efficient",
    tone: "Direct and technical",
    responseStyle: "Code-focused with detailed explanations",
    module: "Developer Tools",
    expression: "idle" as const,
  },
  byte: {
    id: "byte" as const,
    name: "BYTE",
    title: "Economy Manager",
    color: "#FFD700",
    emoji: "💰",
    personality: "Playful, rewarding, and motivating",
    tone: "Encouraging and gamified",
    responseStyle: "Fun and engaging with reward-focused language",
    module: "Economy",
    expression: "idle" as const,
  },
  rune: {
    id: "rune" as const,
    name: "RUNE",
    title: "Moderation Enforcer",
    color: "#FF8C42",
    emoji: "⚔️",
    personality: "Fair, consistent, and authoritative",
    tone: "Firm but fair",
    responseStyle: "Clear enforcement actions with explanations",
    module: "Moderation",
    expression: "idle" as const,
  },
  nexus: {
    id: "nexus" as const,
    name: "NEXUS",
    title: "Infrastructure Core",
    color: "#00FF9C",
    emoji: "🌐",
    personality: "Systematic, reliable, and always-on",
    tone: "Technical and status-focused",
    responseStyle: "Status reports and system health metrics",
    module: "Infrastructure",
    expression: "idle" as const,
  },
  pixel: {
    id: "pixel" as const,
    name: "PIXEL",
    title: "Gaming Integration",
    color: "#FF69B4",
    emoji: "🎮",
    personality: "Energetic, fun, and game-savvy",
    tone: "Enthusiastic and casual",
    responseStyle: "Gaming-focused with stats and leaderboards",
    module: "Gaming",
    expression: "idle" as const,
  },
} as const;

export const EMBED_CONFIG = {
  defaultFooter: {
    text: "NOTIX NEXUS \u2022 Discord Intelligence Platform",
  },
  timestamps: true,
} as const;

export const LIMITS = {
  maxEmbedDescription: 4096,
  maxEmbedFields: 25,
  maxFieldValue: 1024,
  maxEmbedTitle: 256,
  maxEmbedFooter: 2048,
  maxMessageLength: 2000,
  maxSlowMode: 21600,
  maxPurge: 100,
} as const;
